### ISSUE TITLE
Go-critic warnings

### ISSUE THREAD

**Issue by Kvaz1r** [thedevsaddam/gojsonq#19]
[go-critic linter](https://github.com/go-critic/go-critic) found some issues , here corresponding log:  

> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\helper.go:45:2: typeS
> witchVar: case 0 can benefit from type switch with assignment
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\helper.go:45:2: typeS
> witchVar: case 1 can benefit from type switch with assignment
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\helper.go:45:2: typeS
> witchVar: case 2 can benefit from type switch with assignment
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\helper.go:45:2: typeS
> witchVar: case 3 can benefit from type switch with assignment
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\helper.go:45:2: typeS
> witchVar: case 4 can benefit from type switch with assignment
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\helper.go:45:2: typeS
> witchVar: case 5 can benefit from type switch with assignment
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\helper.go:45:2: typeS
> witchVar: case 6 can benefit from type switch with assignment
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\jsonq.go:271:3: range
> ValCopy: each iteration copies 48 bytes (consider pointers or indexing)
> check-package: $GOPATH\src\github.com\thedevsaddam\gojsonq\jsonq.go:45:18: typeU
> nparen: could simplify []([]query) to [][]query

In #18 I propose fixing for them

> Why replacerange with for loop? You must create an issue regarding this refactor before sending PR.

Thanks, good point. The way that I made in my PR not very accurate and should be replaced into this one as written in [description to rangeValCopy](https://go-critic.github.io/overview#rangeValCopy-ref).

**Comment by thedevsaddam** [comment]
@Kvaz1r I think the range and current for loop doing the same, see the reason:

```go
package main

import (
	"fmt"

	"github.com/davecgh/go-spew/spew"
)

func main() {
	list := []struct {
		Name string
	}{
		{
			"Tom",
		},
		{
			"Jane",
		},
		{
			"Joe",
		},
	}

	for _, l := range list {
		spew.Dump(&l) // copy object to the same memory address
	}

	fmt.Println("=================================")

	for i := 0; i < len(list); i++ {
		l := list[i] //  declare and initialize new variable, which also copy the object, unless you put reference (l := &list[i])
		spew.Dump(&l)
	}

	fmt.Println("=================================")

	spew.Dump(list)
}

```

**Comment by Kvaz1r** [comment]
@thedevsaddam 
yes, I written this above:

>  The way that I made in my PR not very accurate and should be replaced into this one as written in description to rangeValCopy.

```
for i := range xs {
	x := &xs[i]
        ...
}
```

**Comment by thedevsaddam** [comment]
@Kvaz1r the for loop is not needed as the the slice will be always small. It contains only queries passed by user. I'll revert the loop to for range. I'll keep helper changes. Thank you for the PR 👍
