### ISSUE TITLE
Multiple nested array support

### ISSUE THREAD

**Issue by johndww** [thedevsaddam/gojsonq#33]
Is it possible to traverse multiple nested arrays in this library without knowing the array indexes? I have a scenario that works well with where clauses on the first array, but I haven't had any success with a second array below that.

This is a successful query using Find (but assumes I know the index to each array):

`Find("data.items.[1].nestedA.[3].nestedB.value")`

I've tried many variations of:
`From("data.items").Where("itemValue", "=", "asdf").From("nestedA").Where("nestedBOtherValue", "eq", "fdsa").Find("nestedB.value")` without any luck.

**Comment by thedevsaddam** [comment]
@johndww Can you provide a JSON document related to the query you want?

**Comment by thedevsaddam** [comment]
Can you check the code below (Use `dev` branch): 
```go

package main

import (
	"github.com/davecgh/go-spew/spew"
	"github.com/thedevsaddam/gojsonq"
)

func main() {
	jq := gojsonq.New().File("./data.json").From("arrayOuter")
	jq.WhereEqual("fieldInner", "456")
	jq.More(). //You have a collection of nodes where you can find any item from any node
			From("[0].arrayInner").WhereEqual("field1", "def")
	spew.Dump(jq.Get(), jq.Error())
}

```

**Comment by johndww** [comment]
@thedevsaddam the More() function is fantastic, that's exactly what I need!

**Comment by thedevsaddam** [comment]
@johndww Did not add documentation, it's in `dev` branch and testing mode. Hope you'll find it soon

**Comment by johndww** [comment]
Thanks @thedevsaddam , I look forward to it being merged here. Until then I'll use that branch.

**Comment by thedevsaddam** [comment]
@johndww Use *v2.0*  for `More()` method. See [doc](https://github.com/thedevsaddam/gojsonq/wiki/Queries#more)
