### ISSUE TITLE
Hi everyone, who's using gojsonq in production? 

### ISSUE THREAD

**Issue by thedevsaddam** [thedevsaddam/gojsonq#39]
Hello everyone, I'm just curious any companies or individual using **gojsonq** in production? If you see the post please share with us, I'd like to include their list in Readme. It'll be inspiring to hear from you.

**Comment by alejoloaiza** [comment]
I'm about to used in my company, have a small doubt, is there a way to simulate this SQL behaviour ?
```
SELECT * 
FROM items WHERE (value > 10000 and value < 20000) OR (discount > 900 AND discount < 1000)

```
Not sure if will be like 
`q.From("items).Where("value",">",10000).OrWhere("value","<",20000).Where("discount",">",900).OrWhere("value","<",1000)`

Does OrWhere acts only in relationship with the previous where?
