### ISSUE TITLE
Pluck should return []interface{}

### ISSUE THREAD

**Issue by D1CED** [thedevsaddam/gojsonq#5]
As stated in its description 'Pluck build(s) an array of values form a property of a list of objects' it returns an array (slice) so why not making it clear in the function signature as well.

Edit: This should not lead to incompatibilities as []interface{} is a subset of interface{}. This follows the rule of returning the most specific type possible.
If you still concerned a method Plucks could be added as incremental additions is covered by the Go compatibility guarantee.

The change requires literally adding two characters.

**Comment by thedevsaddam** [comment]
@D1CED I got your point. Basically, to keep the return consistent it returns `interface{}` instead of `[]interface{}`.  Because of other methods like `Get/First/Nth` return `interface{}` and user asserts the type by himself. 

Probably the doc can be updated
