### ISSUE TITLE
Node names with "." characters in them, like foo.example.com

### ISSUE THREAD

**Issue by davecb** [thedevsaddam/gojsonq#54]
I'n looking at ansible inventory data containing hostnames,  of the form "a192.example.com", and wonder how to express a query in gojsonq, for a datum such as "_meta.hostvars.a001.example.com.ZA_SERVER", which has the expected value of "zabbix.example.com"

Right now, it returns the empty string (;-))

**Comment by thedevsaddam** [comment]
Use`SetSeparator` method https://github.com/thedevsaddam/gojsonq/wiki/Configurations#custom-separator

**Comment by davecb** [comment]
Thanks!
