### ISSUE TITLE
Versions newer than v2.3.0 unavailable via go mod

### ISSUE THREAD

**Issue by logicfox** [thedevsaddam/gojsonq#78]
I'm unable to download versions newer than v2.3.0 seem to be unavailable. Per https://pkg.go.dev/github.com/thedevsaddam/gojsonq/?tab=doc v2.3.0 is the latest version. 

Please suggest what I should do to get get v2.5.0.

**Comment by thedevsaddam** [comment]
Yes, there was an issue. Please use the latest version: https://pkg.go.dev/github.com/thedevsaddam/gojsonq/v2?tab=doc
