### ISSUE TITLE
Why interfaces?

### ISSUE THREAD

**Issue by nkev** [thedevsaddam/gojsonq#79]
Thanks for sharing this project. One question. Why do you do this:

```Go
// strStrictContains checks if x contains y
// This is case sensitive search
func strStrictContains(x, y interface{}) (bool, error) {
	xv, okX := x.(string)
	if !okX {
		return false, fmt.Errorf("%v must be string", x)
	}
	yv, okY := y.(string)
	if !okY {
		return false, fmt.Errorf("%v must be string", y)
	}
	return strings.Contains(xv, yv), nil
}
```

...and not this:

```Go
// strStrictContains checks if x contains y
// This is case sensitive search
func strStrictContains(x, y string) (bool) {
	return strings.Contains(xv, yv)
}
```

...or in this case, simply `strings.Contains(xv, yv)` without a wrapper.

In this example, you are only allowing string inputs anyway, so why not use strongly typed strings as input params instead of `interface{}`?

**Comment by nkev** [comment]
Ah, I think I worked it out. It's because all the operations need to implement the same interface, so they can be chained:

```Go
// QueryFunc describes a conditional function which perform comparison
type QueryFunc func(x, y interface{}) (bool, error)
```

**Comment by thedevsaddam** [comment]
I hope you get the answer yourself.
