### ISSUE TITLE
Map[string]interface{} root

### ISSUE THREAD

**Issue by freman** [thedevsaddam/gojsonq#8]
Doesn't seem to work when you don't have nicely sliceable structures.

IE: https://www.iinet.net.au/status/event/events.json

I tried `Where("DRW", "=", "Darwin")` but kept getting nothing back

**Comment by thedevsaddam** [comment]
@freman Could you please provide the full query?

**Comment by freman** [comment]
I tried various forms of

`gojsonq.New().File("./events.json").From(".").Select("eventid").Where("locations.DRW", "=", "Darwin").Get()`

With, and without the from, WhereNotNil, WhereIn. I even tried SortBy("eventid") first

**Comment by thedevsaddam** [comment]
@freman Hey could you please send a PR to to improve the feature.

We need two things to solve the problem:
1.  Supporting nested query in `Where` method. e.g: `Where("users.posts.title" , "=", "hey")`
2. Traversing the `Object` properties

**Comment by thedevsaddam** [comment]
@freman You can convert the object into a list/array and perform the query. From `gosjonq v1.2` it supports the DOT(.) notation in Where clause. As we can't support querying the objects at this time, I'm closing the issue.

**Comment by freman** [comment]
Eh, this defeats the convenience of a library that parses json and makes it searchable. I just switched to streamed decoding.

**Comment by thedevsaddam** [comment]
Can you share the solution you have done for this particular problem?
